# Site settings
title: Jiyee''s GitHub Pages
email: jiyee.sheng@gmail.com
description: >
    Write some pages about iOS development, while self-learning iOS App Develop.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jiyee.github.io" # the base hostname & protocol for your site
twitter_username: jiyee
github_username:  jiyee

# Build settings
markdown: kramdown
