baseURL = 'https://jiyee.io/'
languageCode = 'zh-CN'
title = "Jiyee's I/O"
theme = "cactus"
# disablePathToLower = true

[params]
  colortheme = "white" # dark, light, white, or classic
  description = "A blog for sharing articles and insights about software development."
  mainSection = "posts"
  showAllPostsOnHomePage = true
  postsOnHomePage = 10
  dateFormatToUse = "2000-01-01"
  showProjectsList = true
  projectsUrl = "https://github.com/jiyee"
  rss = true

[params.comments]
  enabled = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[params.social]]
  name = "github"
  link = "https://github.com/jiyee"

[[params.social]]
  name = "email"
  link = "jiyee.sheng@gmail.com" # no need for "mailto:" at the start

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]
  date = [":filename", ":default", ":fileModTime"]

[permalinks]
  post = "/:year/:month/:slug/"

enableRobotsTXT = true
googleAnalytics = "G-SKWM71T1K6" # or G-XXXXXXXX if you are using Google Analytics v4 (gtag.js)
copyright = "Jiyee Sheng" # cactus theme will use site title if copyright is not set
